language: objective-c
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
gemfile:
  - Gemfile
script:
  - cd test
  - bundle install --jobs=3 --retry=3
  - ruby server.rb
  - bundle exec rake ios:clean:all
  - bundle exec rake ios:spec
